# Generated by Django 4.2.23 on 2025-07-30 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='location',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='City name must contain only letters and spaces', regex='^[A-Za-z\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be 10–15 digits only', regex='^\\d{10,15}$')]),
        ),
    ]
